site_name: MatrixMind.Fun
site_url: https://matrixmind.fun
site_author: Xiaochuan Zhang
site_description: <p>这里只有冷静思考，没有浮夸喧哗 </p> 这里只有算法与代码，没有装饰和繁杂

theme:
  name: material
  language: zh
  logo: assets/images/logo.png 
  favicon: assets/images/logo.png 
  features:
    - navigation.tabs
    - toc.follow
    - navigation.top
    - content.code.copy
    - content.action.edit
    - content.tabs.link
    - search.highlight
    - search.suggest
    - header.autohide
  palette:
    - scheme: default
      primary: blue grey
      accent: cyan
      toggle:
        icon: material/weather-night
        name: 深色模式
    - scheme: slate
      primary: blue grey 
      accent: cyan
      toggle:
        icon: material/white-balance-sunny
        name: 浅色模式
  font:
    text: "Noto Sans SC"
    code: "Fira Code"
  icon:
    repo: fontawesome/brands/github

repo_url: https://github.com/zhangxiaochuan
repo_name: GitHub
edit_uri: edit/main/docs/

markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.magiclink
  - pymdownx.emoji
  - pymdownx.keys
  - pymdownx.tasklist:
      custom_checkbox: true
  - footnotes
  - attr_list
  - def_list
  - tables

extra_javascript:
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - https://unpkg.com/glightbox/dist/js/glightbox.min.js
  - https://cdn.jsdelivr.net/npm/particles.js@2.0.0/particles.min.js
  - javascripts/config.js # <-- 新增一个配置文件引用
  
extra_css:
  - stylesheets/brand.css
  # - stylesheets/extra.css
  - https://unpkg.com/glightbox/dist/css/glightbox.min.css

plugins:
  - search
  - glightbox
  - search
  - macros

nav:
  - Posts: posts/index.md
  - Tags: tags/index.md
  - Projects: projects/index.md
  - About: about/index.md